### PR TITLE
23 component typography

### PR DESCRIPTION
**Pull request by daniknewgarden**
Related to #23.
# Changes: 
Introduce a new `Typography` component.

### CODE REVIEW

**Comment by daniknewgarden** [comment]
Hey @lulek1410. Could you please take a look at the code and check the publishes storybook (make UI review and check UI tests)?

**Comment by lulek1410** [comment]
The code looks good to me but there seems to be kind of a problem in storybook. When trying to change controls value for variant i get:
image
This is not realy a big problem, maybe we can let it be. It's for you to decide i guess.

Also there seems to be more "variants" (labels) in the figma project. Do you intend to implement them separately as they have slightly different styling?

**Comment by daniknewgarden** [comment]
I will try to fix a problem with the storybook. 
And about labels: I want to make them as a different component, a label for the forms. It will be a part of a different milestone, where we will develop form elements.

**Comment by daniknewgarden** [comment]
Fixed storybook. Just added select control with hardcoded values

**Review by lulek1410 — APPROVED** [review]

**Pull request merged**
